Library/urls.py
from django.contrib import admin
from django.urls import path
from.views import *

app_name = 'Library'


urlpatterns = [
    path('home/', addata,name='addata'),
    # path('show_squad/',show_squad, name='addshow'), 
    path('delete_data/<int:id>/',delete_data, name='delete_data'), 
    path('<int:id>/',update_data, name='update_data'),
]

PersonalProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Library.urls'))
]

Library/models.py
from django.db import models

# Create your models here.
class Address(models.Model):
    name = models.CharField(max_length=70)
    city = models.CharField(max_length=70)
    state = models.CharField(max_length=70)
    mbno = models.CharField(max_length=70)

Library/forms.py
from django.core import validators
from django import forms
from .models import Address

class AddressBook(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['name', 'city', 'state', 'mbno']
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'city':forms.TextInput(attrs={'class':'form-control'}),
            'state':forms.TextInput(attrs={'class':'form-control'}),
            'mbno':forms.TextInput(attrs={'class':'form-control'}),
            
        }

Library/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect,HttpResponseRedirect
import requests
from .forms import AddressBook
from .models import Address
from numpy import delete


# Create your views here.

def addata(request):
    if request.method == 'POST':
        fm1 = AddressBook(request.POST)
        if fm1.is_valid():
            nm = fm1.cleaned_data['name']
            ct = fm1.cleaned_data['city']
            st = fm1.cleaned_data['state']
            mb = fm1.cleaned_data['mbno']
            make = Address(name=nm, city=ct, state=st, mbno=mb)
            make.save()
            fm1 = AddressBook()
    else:
        fm1 = AddressBook()
    result = Address.objects.all()
    return render(request,'project/index.html',{'form':fm1, 'result':result})

def delete_data(request, id):
    if request.method == 'POST':
        pi = Address.objects.get(pk=id)
        pi.delete()
        return HttpResponseRedirect('/home') 

def update_data(request, id):
    if request.method == 'POST':
        pi = Address.objects.get(pk=id)
        fm1 = AddressBook(request.POST, instance=pi)
        if fm1.is_valid():
            fm1.save()
    else:
        pi = Address.objects.get(pk=id)
        fm1 = AddressBook(instance=pi)
    return render(request,'project/update.html', {'form':fm1})

templates/project/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <title>ALLbloG | ALL in ONE</title> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/style.css"> -->

	<link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">

	<link rel="stylesheet"
  href="https://unpkg.com/boxicons@latest/css/boxicons.min.css">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>

</head>
<body>
<div class="container mt-5">
  <h2 class="text-center alert alert-danger">
    AddresBook - create you Address Here
  </h2>
  {% block content %}    {% endblock content %}
</div>



</body>
</html>

templates/project/index.html
{% extends 'project/base.html' %}
{% load static %}
{% block content %}
<div class="container">
<div class="row">
    <div class="row col-sm-4">
        <h4 class="text-center alert alert-info">Add New Address</h4>

<form action="" method="POST">
    {% csrf_token %}
   {{form.as_p}} <br>
   <input type="submit" class="btn btn-success" value="Add " style="margin-left: 0px; padding: 10px 30px;" >
</form>
</div>
<div class="col-sm-7 offset-1">
    <h4 class="text-center alert alert-info"> Your Address Details</h4>
    {% if result %}
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Person Name</th>
            <th scope="col">City Name</th>
            <th scope="col">State Name</th>
            <th scope="col">Mobile Number</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
            {% for st in result %}
          <tr>
            <th scope="row">{{st.id}}</th>
            <td>{{st.name}}</td>
            <td>{{st.city}}</td>
            <td>{{st.state}}</td>
            <td>{{st.mbno}}</td>
            <td>
                <a href="{% url 'Library:update_data' st.id %}" class="btn btn-warning btn-sm">Edit</a>
                <form action=" {% url 'Library:delete_data' st.id %} " method="post"  style="display: inline;">{% csrf_token %}
                    <input type="submit" class="btn btn-danger" value="Delete">
                </form>
            </td>
          </tr>
         {% endfor %}
        </tbody>
      </table>
    {% else %}
    <h1 class="text-center alert alert-warning"> No data</h1>
    {% endif %}

    
</div>
</div>
</div>
{% endblock %}

templates/project/index1.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="stylesheet" href="{% static 'templatemo-space-dynamic.css' %}">
  <!-- {%block css%}
<link rel="stylesheet" href="/static/templatemo-space-dynamic.css">
{%endblock%} -->

  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

  <title>ALL BLOG | HOME</title>

  <!-- Bootstrap core CSS -->
  <!-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->

  <!-- Additional CSS Files -->
  <!-- <link rel="stylesheet" href="{% static 'fontawesome.css' %}"> -->
  


  <!-- TemplateMo 562 Space Dynamic

https://templatemo.com/tm-562-space-dynamic
 -->

</head>

<body>


  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky wow slideInDown">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="main-nav">
          
            <a href="index.html" class="logo">
              <h4><img src="\static\images\logo.png" style="width: 70px; height: 50px;">ALL<span>blog</span></h4>
            </a>
            
            <ul class="nav">
              <li class="scroll-to-section"><a href="#top" class="active">Home</a></li>
              <li class="scroll-to-section"><a href="#about">About Us</a></li>
              <li class="scroll-to-section"><a href="#services">Services</a></li>
              <li class="scroll-to-section"><a href="#portfolio">Portfolio</a></li>
              <li class="scroll-to-section"><a href="#blog">Blog</a></li>
              <li class="scroll-to-section"><a href="#contact">Message Us</a></li>
              <li class="scroll-to-section">
                <div class="main-red-button"><a href="#contact">Contact Now</a></div>
              </li>
            </ul>
            <a class='menu-trigger'>
              <span>Menu</span>
            </a>
            <!-- ***** Menu End ***** -->
          </nav>
        </div>
      </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->

  <br>
  <br><br><br><br>
  <br><br><br><br>

  <br><br><br><br>
  <br><br><br><br>

  <br><br><br><br>

  <br><br><br><br>

  <!-- Start: Footer -->
 
  <div class="container" align="center">
    <div class="row">
      <div class="col-sm-4">
        <div id=" text-2">
          <h3 class="footer-widget-title">About Libraria</h3>
          <span class="underline left"></span>
          <div class="textwidget">
            It is a long established fact that a reader will be distracted by the readable content of a page when
            looking.
          </div>
          <address>
            <div class="info">
              <i class="fa fa-location-arrow"></i>
              <span>21 King Street, Melbourne, Victoria 3000 Australia</span>
            </div>
            <div class="info">
              <i class="fa fa-envelope"></i>
              <span><a href="mailto:support@libraria.com">support@libraria.com</a></span>
            </div>
            <div class="info">
              <i class="fa fa-phone"></i>
              <span><a href="tel:012-345-6789">+ 012-345-6789</a></span>
            </div>
          </address>
        </div>
      </div>
      <div class="col-sm-2">
        <div id=" nav_menu-2" class="widget widget_nav_menu">
          <h3 class="footer-widget-title">Quick Links</h3>
          <span class="underline left"></span>
          <div class="menu-quick-links-container">
            <ul id="menu-quick-links" class="menu">
              <li><a href="#">Library News</a></li>
              <li><a href="#">History</a></li>
              <li><a href="#">Meet Our Staff</a></li>
              <li><a href="#">Board of Trustees</a></li>
              <li><a href="#">Budget</a></li>
              <li><a href="#">Annual Report</a></li>
            </ul>
          </div>
        </div>
        </div>
        <div class="col-sm-2">
          <div id=" text-4">
            <h3 class="footer-widget-title">Timing</h3>
            <span class="underline left"></span>
            <div class="timming-text-widget">
              <time datetime="2017-02-13">Mon - Thu: 9 am - 9 pm</time>
              <time datetime="2017-02-13">Fri: 9 am - 6 pm</time>
              <time datetime="2017-02-13">Sat: 9 am - 5 pm</time>
              <time datetime="2017-02-13">Sun: 1 pm - 6 pm</time>
              <ul>
                <li><a href="#">Closings</a></li>
                <li><a href="#">Branches</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class=" widget twitter-widget">
            <h3 class="footer-widget-title">Latest Tweets</h3>
            <span class="underline left"></span>
            <div id="twitter-feed">
              <ul>
                <li>
                  <p><a href="#">@TemplateLibraria</a> Sed ut perspiciatis unde omnis iste natus error sit voluptatem. <a
                      href="#">template-libraria.com</a></p>
                </li>
                <li>
                  <p><a href="#">@TemplateLibraria</a> Sed ut perspiciatis unde omnis iste natus error sit voluptatem. <a
                      href="#">template-libraria.com</a></p>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="sub-footer">
      <div class="container">
        <div class="row">
          <div class="footer-text col-md-3">
            <p><a target="_blank" href="https://www.templateshub.net">Templates Hub</a></p>
          </div>
          <div class="col-md-9 pull-right">
            <ul>
              <li id="last"><a href="index-2.html">Home</a></li>
              <li id="last"><a href="books-media-list-view.html">Books &amp; Media</a></li>
              <li id="last"><a href="news-events-list-view.html">News &amp; Events</a></li>
              <li id="last"><a href="#">Kids &amp; Teens</a></li>
              <li id="last"><a href="services.html">Services</a></li>
              <li id="last"><a href="#">Research</a></li>
              <li id="last"><a href="blog.html">Blog</a></li>
              <li id="last"><a href="contact.html">Contact</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <style>
      #last{
        float: left;
      }
    </style>
</body>

</html>

templates/project/update.html
{% extends 'project/base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-sm-8 offset-2">
        <h4 class="alert alert-info>Update Content">Update Your Information</h4> 


        <form action="" method="POSt">
            {% csrf_token %}
            {{form.as_p}} <br>
            <input type="submit" class="btn btn-info" value="Update">
            <a href="{% url 'Library:addata'  %}" class="btn btn-success">Back to Home</a>
        </form>
    </div>
    
</div>
{% endblock %}